name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: Pacific-Agency/workflows/.github/workflows/lint.yml@v0.1.0
  test:
    uses: Pacific-Agency/workflows/.github/workflows/test.yml@v0.1.0
