name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: Pacific-Agency/workflows/.github/workflows/frontend-lint.yml@v0.2.1
  test:
    uses: Pacific-Agency/workflows/.github/workflows/frontend-test.yml@v0.2.1
