name: Обновление версии в `package.json`

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия для package.json"
        required: true
        type: string

jobs:
  update-package-json:
    uses: Pacific-Agency/workflows/.github/workflows/update-package-json.yml@v0.1.1
    with:
      version: ${{ inputs.version }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
